
name: CI

on:
  push:

  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-node@v1

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: test
      run: |
        (cd ~ && GO111MODULE=on go get github.com/ysmood/kit/cmd/godev)
        go generate
        godev -l
